// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2KahrQy-BDS73svB9C_PL0h1_crK2E0',
    appId: '1:66917612436:web:9a1e4b5731943f56e7ad81',
    messagingSenderId: '66917612436',
    projectId: 'uniprep-cd57b',
    authDomain: 'uniprep-cd57b.firebaseapp.com',
    storageBucket: 'uniprep-cd57b.firebasestorage.app',
    measurementId: 'G-09QLYDRDM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn6A1qzPK-TJrKWsA9gJpRynUsfsq3Mxo',
    appId: '1:66917612436:android:63a0ce298937b275e7ad81',
    messagingSenderId: '66917612436',
    projectId: 'uniprep-cd57b',
    storageBucket: 'uniprep-cd57b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg4JmGSsu8AxVahmkMr1kt0myjZd0KKEM',
    appId: '1:66917612436:ios:b24ad3bae2522810e7ad81',
    messagingSenderId: '66917612436',
    projectId: 'uniprep-cd57b',
    storageBucket: 'uniprep-cd57b.firebasestorage.app',
    iosClientId: '66917612436-d3t0hobksb9pai1plq9am2jsnepelkmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniprep',
  );
}
